apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-bullmq
    app.kubernetes.io/managed-by: Helm
  name: nestjs-bullmq
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nestjs-bullmq
  type: NodePort
status:
  loadBalancer: {}
